/**
 * Meta Society — Simulation Lab engine.
 *
 * Public surface. Everything here is deterministic given
 * (population, policy vector, engine version, seed) and produces no content
 * generated by a language model.
 */

export * from "./types";
export { createRng, fnv1a } from "./rng";
export {
  CENSUS,
  CENSUS_DERIVED,
  CHANNEL_LAGS_MONTHS,
  FIELD_LEDGER,
  PILGRIMAGE_WARDS,
  SECTOR_COMPOSITION,
  SECTOR_TASK_EXPOSURE,
  TOWN_DISTRICT,
  TOWN_ID,
  TOWN_NAME,
  WARD_ZONE_MAP,
  ledgerCounts,
  ledgerTable,
} from "./census";
export { GENERATOR_VERSION, clonePopulation, generatePopulation, populationComposition, validatePopulation } from "./population";
export {
  AGGREGATE_NODES,
  BN_VERSION,
  DOMAINS,
  DOMAIN_LEGENDS,
  FEEDBACK_NODES,
  MICRO_NODES,
  NODE_REGISTRY,
  TOWN_NODES,
  buildBn,
  applyEvidence,
  assertEvidenceIsUpstream,
  causalAttribution,
  compileBn,
  interventionEffect,
  policyResponse,
  posteriorDistribution,
  samplePass,
  withIntervention,
  validateBnDirection,
  type NodeSpec,
} from "./bn";
export {
  CHANNEL_ENGINE_FAMILY,
  allocationFor,
  channelParams,
  channelsUseAllocation,
  directTargetsFor,
  engineInstrumentFor,
  hasChannel,
  pendingChannelNodes,
  selectedChannels,
} from "./instruments";
export {
  CHANNELS,
  DECLARED_CHANNELS,
  IMPLEMENTED_CHANNELS,
  composePolicy,
  suggestChannels,
  type ChannelDefinition,
  type ChannelParam,
  type ChannelStatus,
  type ComposedPolicy,
} from "./channel-dictionary";
export {
  LOWER_IS_BETTER,
  METRIC_LABELS,
  METRIC_UNITS,
  SECTOR_PRODUCTIVITY,
  checkIdentities,
  computeLevels,
  incomeClassHistogram,
  incomeHistogram,
  sentimentHistogram,
  zoneGdpLevel,
  zoneMetrics,
  zonePopulations,
} from "./aggregate";
export { crowdingDistance, differentialEvolution, dominates, nonDominatedSort, paretoFront, randomSearch } from "./de";
export { createDecisionEngine, createJevDecisionEngine, createLlmDecisionEngine, createRuleDecisionEngine } from "./decision";
export {
  CONFIDENCE_ROUNDS,
  DE_BOUNDS,
  OBJECTIVE_LABELS,
  REFERENCE_BUDGET,
  decodeVector,
  encodePolicy,
  getPopulation,
  intervalFor,
  rampFor,
  runSimulation,
  type SimulationOptions,
} from "./simulate";
export {
  bestInLineage,
  describeLineageKey,
  lineageHistory,
  lineageKeyFor,
  policyDistance,
  type LineageRecord,
} from "./lineage";
