/**
 * Meta Society — Simulation Lab engine.
 *
 * Public surface. Everything here is deterministic given
 * (population, policy vector, engine version, seed) and produces no content
 * generated by a language model.
 */

export * from "./types";
export { createRng, fnv1a } from "./rng";
export {
  CENSUS,
  CENSUS_DERIVED,
  CHANNEL_LAGS_MONTHS,
  FIELD_LEDGER,
  PILGRIMAGE_WARDS,
  SECTOR_COMPOSITION,
  SECTOR_TASK_EXPOSURE,
  TOWN_DISTRICT,
  TOWN_ID,
  TOWN_NAME,
  WARD_ZONE_MAP,
  ledgerCounts,
  ledgerTable,
} from "./census";
export { GENERATOR_VERSION, clonePopulation, generatePopulation, populationComposition, validatePopulation } from "./population";
export {
  AGGREGATE_NODES,
  BN_VERSION,
  DOMAINS,
  DOMAIN_LEGENDS,
  FEEDBACK_NODES,
  MICRO_NODES,
  TOWN_NODES,
  buildBn,
  applyEvidence,
  assertEvidenceIsUpstream,
  causalAttribution,
  compileBn,
  interventionEffect,
  policyResponse,
  posteriorDistribution,
  withIntervention,
  validateBnDirection,
} from "./bn";
export {
  LOWER_IS_BETTER,
  METRIC_LABELS,
  METRIC_UNITS,
  SECTOR_PRODUCTIVITY,
  checkIdentities,
  computeLevels,
  incomeClassHistogram,
  incomeHistogram,
  sentimentHistogram,
  zoneGdpLevel,
  zoneMetrics,
  zonePopulations,
} from "./aggregate";
export { crowdingDistance, differentialEvolution, dominates, nonDominatedSort, paretoFront, randomSearch } from "./de";
export { createDecisionEngine, createJevDecisionEngine, createLlmDecisionEngine, createRuleDecisionEngine } from "./decision";
export {
  DEFAULT_SCENARIO,
  DE_BOUNDS,
  OBJECTIVE_LABELS,
  REFERENCE_BUDGET,
  SCENARIO_PRESETS,
  decodeVector,
  encodePolicy,
  getPopulation,
  intervalFor,
  rampFor,
  runSimulation,
  type SimulationOptions,
} from "./simulate";
