/**
 * Policy genome — the structured, historically-meaningful description of a
 * proposed policy that GGG matches against real historical predecessors.
 *
 * WHY A GENOME AND NOT THE POLICY VECTOR. The engine's `PolicyVector` is a small
 * real-valued tuple (intensity, budget, duration, allocation, channels). That is
 * enough to RUN a policy but not enough to say WHAT it is: its mechanism, target
 * population, context, delivery route, resource scale and causal pathway. Those
 * qualitative characteristics are the inherited information GGG transfers, and
 * they are what makes a housing policy structurally different from an
 * employment policy even when both are "government programmes".
 *
 * The genome contains no invented numbers. Its numeric fields (budget, duration)
 * are read from the policy; its qualitative fields are derived deterministically
 * from the channel dictionary and the brief. Nothing here is generated by a
 * language model.
 */

import { CHANNELS } from "./channel-dictionary";
import { selectedChannels } from "./instruments";
import { channelDomainsFor, type PolicyBrief } from "./policy-brief";
import { REFERENCE_BUDGET } from "./simulate";
import { GOVERNANCE_REGISTRY, type GovernanceLevel } from "./governance";
import type { EvidenceStrength } from "./evidence";
import type { MetricKey, PolicyVector } from "./types";

/* ------------------------------------------------------------------ */
/* Shape                                                               */
/* ------------------------------------------------------------------ */

export type GenomeContext = "urban" | "rural" | "mixed";
export type GenomeSeasonality = "none" | "seasonal";
export type GenomeScale = "local" | "district" | "state" | "national";

/** A resource-intensity band derived from the policy's own budget. */
export type ResourceBand = "low" | "medium" | "high";

export interface PolicyGenome {
  name: string;
  channelIds: string[];
  domains: string[];

  /** The causal mechanism the policy participates in, in words. */
  mechanism: string;
  /** Fine-grained mechanism tags used by similarity scoring. */
  mechanismTags: string[];

  targetPopulation: string;
  targetTraits: string[];

  context: GenomeContext;
  seasonality: GenomeSeasonality;

  /** The administrative level the policy is decided at. */
  authorityLevel: GovernanceLevel;
  /** Resource scale of the policy, from its budget and authority. */
  scale: GenomeScale;

  budgetInr: number;
  resourceBand: ResourceBand;
  durationMonths: number;
  intensity: number;

  /** Delivery / implementation tags. */
  delivery: string[];

  /** Bayesian-network nodes the policy's channels may move. */
  bnNodes: string[];
  /** Metrics the policy's channels declare as direct targets. */
  directTargets: MetricKey[];

  /**
   * How strong the DIRECTION evidence for this genome's mechanism is. Supplied
   * by GGG after matching; "uncalibrated" until then.
   */
  evidenceQuality: EvidenceStrength;

  /** Human-readable provenance of every derived field. */
  provenance: string[];
}

/* ------------------------------------------------------------------ */
/* Channel genome profiles                                             */
/* ------------------------------------------------------------------ */

interface GenomeProfile {
  mechanism: string;
  mechanismTags: string[];
  targetTraits: string[];
  context: GenomeContext;
  seasonality: GenomeSeasonality;
  delivery: string[];
}

/**
 * A deterministic profile per engine channel. These describe the CHARACTERISTIC
 * a channel implies, not an outcome: they are the vocabulary GGG matches on.
 */
export const CHANNEL_GENOME_PROFILE: Record<string, GenomeProfile> = {
  INCOME_SUPPORT: {
    mechanism: "Direct income support that changes disposable income for a target group.",
    mechanismTags: ["cash_transfer", "income_support", "demand_injection"],
    targetTraits: ["low_income", "informal"],
    context: "urban",
    seasonality: "none",
    delivery: ["transfer_payment"],
  },
  LABOR_MARKET: {
    mechanism: "Labour-market intervention that raises access to work, wages or skills.",
    mechanismTags: ["wage_employment", "skill_training", "livelihood", "placement"],
    targetTraits: ["informal", "unskilled", "low_income"],
    context: "urban",
    seasonality: "none",
    delivery: ["training_provider", "placement", "public_works"],
  },
  HOUSING: {
    mechanism: "Housing assistance that improves dwelling quality and reduces housing stress.",
    mechanismTags: ["housing_assistance", "construction", "affordability"],
    targetTraits: ["low_income", "housing_stress"],
    context: "urban",
    seasonality: "none",
    delivery: ["construction_subsidy", "housing_credit"],
  },
  EDUCATION_SKILL: {
    mechanism: "Education or human-capital investment with a long lag before it pays off.",
    mechanismTags: ["human_capital", "schooling", "skill_training"],
    targetTraits: ["school_going", "children", "working_age"],
    context: "urban",
    seasonality: "seasonal",
    delivery: ["school", "training_provider"],
  },
  TAX_FISCAL: {
    mechanism: "Fiscal/rate change that redistributes or raises public revenue.",
    mechanismTags: ["taxation", "fiscal", "revenue"],
    targetTraits: ["taxpayer", "formal"],
    context: "urban",
    seasonality: "none",
    delivery: ["tax_administration"],
  },
  REGULATION: {
    mechanism: "Rule-making and enforcement that changes how a market or activity operates.",
    mechanismTags: ["regulation", "enforcement", "compliance"],
    targetTraits: ["business", "formal"],
    context: "urban",
    seasonality: "none",
    delivery: ["licensing", "inspection"],
  },
  HEALTHCARE_ACCESS: {
    mechanism: "Coverage expansion that reduces out-of-pocket health cost.",
    mechanismTags: ["health_coverage", "insurance", "out_of_pocket"],
    targetTraits: ["low_income", "informal"],
    context: "urban",
    seasonality: "none",
    delivery: ["coverage_eligibility", "empanelled_provider"],
  },
  DIGITAL_ACCESS: {
    mechanism: "Digital connectivity or identity that lowers transaction costs.",
    mechanismTags: ["digital", "connectivity", "transaction_cost"],
    targetTraits: ["residents"],
    context: "urban",
    seasonality: "none",
    delivery: ["network_rollout"],
  },
  ENVIRONMENT_CLIMATE: {
    mechanism: "Environmental or climate-resilience rules and investment.",
    mechanismTags: ["environment", "resilience", "regulation"],
    targetTraits: ["residents"],
    context: "urban",
    seasonality: "seasonal",
    delivery: ["regulation", "capital_works"],
  },
  FOOD_SECURITY: {
    mechanism: "Ration, price support or nutrition provision.",
    mechanismTags: ["food", "nutrition", "in_kind_transfer"],
    targetTraits: ["low_income", "children"],
    context: "mixed",
    seasonality: "seasonal",
    delivery: ["food_delivery"],
  },
  INFRASTRUCTURE: {
    mechanism: "Physical infrastructure investment with a long build lag.",
    mechanismTags: ["infrastructure", "capital_works", "land_acquisition", "construction"],
    targetTraits: ["residents", "landholders"],
    context: "urban",
    seasonality: "none",
    delivery: ["state_agency", "capital_works", "contractor"],
  },
  FINANCIAL_INCLUSION: {
    mechanism: "Credit or banking access through which informal actors obtain working capital.",
    mechanismTags: ["micro_credit", "working_capital", "informal_commerce"],
    targetTraits: ["informal", "self_employed", "low_income"],
    context: "urban",
    seasonality: "none",
    delivery: ["bank_credit", "digital_payment"],
  },
  PILGRIMAGE_FACILITIES: {
    mechanism:
      "Wari-facing facilities and seasonal capacity — sanitation, rest areas, crowd management, lodging, transit and pilgrim welfare.",
    mechanismTags: ["pilgrimage", "seasonal", "sanitation", "crowd_management", "access"],
    targetTraits: ["pilgrimage", "temporary_visitors", "seasonal"],
    context: "urban",
    seasonality: "seasonal",
    delivery: ["seasonal_capacity", "civic_services"],
  },
};

function resourceBandFor(budgetInr: number): ResourceBand {
  const share = budgetInr / REFERENCE_BUDGET;
  return share < 0.25 ? "low" : share < 0.6 ? "medium" : "high";
}

/**
 * Scale band of the policy, from the deciding authority's level and the budget.
 * A local body spending the reference envelope stays "local"; a state-level
 * authority is at least "state".
 */
function scaleFor(authorityLevel: GovernanceLevel, budgetInr: number): GenomeScale {
  const order: GovernanceLevel[] = ["local", "district", "state", "national"];
  const base = order.indexOf(authorityLevel);
  const budgetLift = budgetInr >= REFERENCE_BUDGET ? 1 : 0;
  const idx = Math.min(order.length - 1, base + budgetLift);
  return (["local", "district", "state", "national"] as GenomeScale[])[idx];
}

/* ------------------------------------------------------------------ */
/* Derivation                                                          */
/* ------------------------------------------------------------------ */

/**
 * Derive the genome of a proposed policy. Pure and deterministic: the same
 * policy and brief always produce the same genome.
 */
export function genomeFromPolicy(policy: PolicyVector, brief?: PolicyBrief): PolicyGenome {
  const channels = selectedChannels(policy.channelIds);
  const profiles = channels.map((c) => CHANNEL_GENOME_PROFILE[c.id]).filter(Boolean);

  const mechanismTags = unique(profiles.flatMap((p) => p.mechanismTags));
  const targetTraits = unique(profiles.flatMap((p) => p.targetTraits));
  const delivery = unique(profiles.flatMap((p) => p.delivery));
  const mechanisms = unique(profiles.map((p) => p.mechanism));

  const hasSeasonal = profiles.some((p) => p.seasonality === "seasonal");
  const contexts = new Set(profiles.map((p) => p.context));
  const context: GenomeContext =
    contexts.size === 1 ? [...contexts][0] : contexts.size === 0 ? "urban" : "mixed";

  const authorityLevel: GovernanceLevel = brief
    ? GOVERNANCE_REGISTRY[brief.governance.primaryDecisionAuthority]?.level ?? "local"
    : "local";

  const bnNodes = unique(channels.flatMap((c) => c.bnNodes));
  const directTargets = unique(channels.flatMap((c) => c.directTargets));

  return {
    name: policy.name,
    channelIds: [...policy.channelIds],
    domains: brief ? brief.domains : channelDomainsFor(policy.channelIds),
    mechanism: mechanisms.join(" ").trim() || "No modelled mechanism (no implemented channel selected).",
    mechanismTags,
    targetPopulation: brief?.target.description ?? "Not specified",
    targetTraits,
    context,
    seasonality: hasSeasonal ? "seasonal" : "none",
    authorityLevel,
    scale: scaleFor(authorityLevel, policy.budget),
    budgetInr: policy.budget,
    resourceBand: resourceBandFor(policy.budget),
    durationMonths: policy.durationMonths,
    intensity: policy.intensity,
    delivery,
    bnNodes,
    directTargets,
    evidenceQuality: "uncalibrated",
    provenance: [
      `mechanism tagged from channel dictionary: ${policy.channelIds.join(", ") || "none"}`,
      `context derived from channel profiles: ${context}`,
      `scale derived from deciding authority (${authorityLevel}) and budget band (${resourceBandFor(policy.budget)})`,
      brief ? "target population read from the policy brief" : "no brief supplied; target unspecified",
    ],
  };
}

function unique<T>(items: T[]): T[] {
  return [...new Set(items)];
}

/** True when a channel's genome profile exists (i.e. the channel is wired). */
export function hasGenomeProfile(channelId: string): boolean {
  return Boolean(CHANNEL_GENOME_PROFILE[channelId]) && Boolean(CHANNELS[channelId]);
}
